name: CI

on:
  push:

jobs:
  compiling:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test
