name: CI


on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:

      - name: Get code
        uses: actions/checkout@v4
      

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with: 
          node-version: 22
  
      - name: Install packages
        run: npm install
      
    
      - name: Build project
        run: npm run build
  
      - name: Run tests
        run: npm run test
