name: CI

on:
  push:

jobs:
  compiling:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Install remover
        run: npm install -g ts-remove-unused-imports

      - name: Remove unused imports
        run: ts-remove-unused-imports "src/**/*.ts"

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: remove unused imports"
          branch: ${{ github.ref_name }}
